CREATE TABLE Usuario (
    ID_USUARIO SERIAL PRIMARY KEY,
    TIPO_USUARIO VARCHAR(20) NOT NULL CHECK (TIPO_USUARIO IN ('Usuario', 'Administrador', 'Entregador')),
    EMAIL_USUARIO VARCHAR(255) NOT NULL UNIQUE,
    LOGIN_USUARIO VARCHAR(100) NOT NULL UNIQUE,
    SENHA_USUARIO VARCHAR(255) NOT NULL,
    FORMA_PAGAMENTO_DEFAULT_USUARIO INT REFERENCES Formas_Pagamento_Usuario(ID_FORMA_PAGAMENTO_USUARIO),
    ENDERECO_USUARIO TEXT NOT NULL
);

CREATE TABLE Carrinho (
    ID_CARRINHO SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL REFERENCES Usuario(ID_USUARIO)
);

CREATE TABLE Itens_Carrinho (
    ID_ITEM_CARRINHO SERIAL PRIMARY KEY,
    ID_CARRINHO INT NOT NULL REFERENCES Carrinho(ID_CARRINHO),
    ID_CUPCAKE INT NOT NULL REFERENCES Cupcake(ID_CUPCAKE)
);

CREATE TABLE Cupcake (
    ID_CUPCAKE SERIAL PRIMARY KEY,
    VALOR_CUPCAKE NUMERIC(10, 2) NOT NULL,
    DESCRICAO_CUPCAKE TEXT NOT NULL,
    QUANTIDADE_DISPONIVEL_CUPCAKE INT NOT NULL
);

CREATE TABLE Pedido (
    ID_PEDIDO SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL REFERENCES Usuario(ID_USUARIO),
    DATA_INICIAL_PEDIDO DATE NOT NULL,
    DATA_FINALIZACAO_PEDIDO DATE,
    STATUS_PEDIDO VARCHAR(20) NOT NULL CHECK (STATUS_PEDIDO IN ('Solicitado', 'Aceito', 'Em preparo', 'Pronto', 'Enviado', 'Finalizado', 'Cancelado'))
);

CREATE TABLE Itens_Pedido (
    ID_ITEM_PEDIDO SERIAL PRIMARY KEY,
    ID_PEDIDO INT NOT NULL REFERENCES Pedido(ID_PEDIDO),
    ID_CUPCAKE INT NOT NULL REFERENCES Cupcake(ID_CUPCAKE)
);

CREATE TABLE Formas_Pagamento (
    ID_FORMA_PAGAMENTO SERIAL PRIMARY KEY,
    TIPO_FORMA_PAGAMENTO VARCHAR(20) NOT NULL CHECK (TIPO_FORMA_PAGAMENTO IN ('Cartao', 'Pix', 'Entrega'))
);

CREATE TABLE Formas_Pagamento_Usuario (
    ID_FORMA_PAGAMENTO_USUARIO SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL REFERENCES Usuario(ID_USUARIO),
    ID_FORMA_PAGAMENTO INT NOT NULL REFERENCES Formas_Pagamento(ID_FORMA_PAGAMENTO),
    INFORMACOES_FORMA_PAGAMENTO JSON NOT NULL
);
